### ISSUE TITLE
[Android] error while retrieving images in the loop

### ISSUE THREAD

**Issue by amarchenko25** [cloudacy/pdf_image_renderer#1]
Hi,
When I try to get all images from pdf I got an error:

> PlatformException(INVALID_ARGUMENTS, PDF 72 already has an open page., null, null)

It occurs only for **Android** devices. So, basically, I get the first image correctly, but the second one not.
Here is my code method:
```
Future<List<Uint8List>> getPdfImages(String tempFilePath) async {
  final images = <Uint8List>[];
  
  final pdf = PdfImageRendererPdf(path: tempFilePath);
  await pdf.open();
  
  final pageCount = await pdf.getPageCount();
  
  for (var i = 0; i < pageCount; i++) {
    final size = await pdf.getPageSize(pageIndex: i);
    final image = await pdf.renderPage(
      pageIndex: i,
      x: 0,
      y: 0,
      width: size.width,
      height: size.height,
      scale: 1,
    );
  
    if (image != null) {
      images.add(image);
    }
  }
  
  await pdf.close();
  
  return images;
}
```
Could you please have a look at this issue?

**Comment by d-kuen** [comment]
Hi @amag2511,

thank you for submitting this issue.

The code provided by you should be fine.

We found the bug and fixed it at https://github.com/cloudacy/pdf_image_renderer/commit/21a0d45aa9a096760dd03763b4a961d9d9b9450c.

We will create a release soon, which includes https://github.com/cloudacy/pdf_image_renderer/commit/21a0d45aa9a096760dd03763b4a961d9d9b9450c. I will get back to you, once the release is pushed to GitHub.

**Comment by d-kuen** [comment]
Version [0.5.2](https://pub.dev/packages/pdf_image_renderer/changelog#051) includes the fix.

Please update to this version or higher.

Thanks again.
