### ISSUE TITLE
Password Protected PDF

### ISSUE THREAD

**Issue by vishwajit76** [cloudacy/pdf_image_renderer#2]
Provide an option to enter password for password protected pdf.

**Comment by p-kuen** [comment]
This would be a nice feature. Unfortunately we don't have the time to implement this feature right now, but we would be happy to review a PR from you or another contributor.

**Comment by chaudharydeepanshu** [comment]
I think I can help with this maybe using [PdfBox-Android](https://github.com/TomRoush/PdfBox-Android) but not sure will have to look more into it.

But how should we provide this functionality?

What I'm thinking of doing is by providing a separate method to check if the document is encrypted or not and also allow providing the user and owner password in the `PdfImageRendererPdf()`.

Let me know what you think of the approach.

**Comment by d-kuen** [comment]
Implemented with https://github.com/cloudacy/pdf_image_renderer/commit/941dc315cf32590a187116958615891114cf1028.
Although Android support is limited to Android 15.0+.
