### ISSUE TITLE
Android 15 error while rendering

### ISSUE THREAD

**Issue by kopianan** [cloudacy/pdf_image_renderer#5]
<img width="1287" alt="Screenshot 2024-12-27 at 10 29 46" src="https://github.com/user-attachments/assets/1b130680-fe1d-4a98-ba8f-6974471e5605" />

error while render pdf to image

**Comment by p-kuen** [comment]
Please provide more information about your setup. Package version, device model, flutter version, etc.

**Comment by hanushkasuren** [comment]
> Please provide more information about your setup. Package version, device model, flutter version, etc.


Same error here. 

Package version : 0.7.0
Device model : Pixel 5 emulator 
Flutter version: 3.24.0 (stable)

Error happens when opening a file

`final pdf = PdfImageRendererPdf(path: path);await pdf.open();`

**Comment by hanushkasuren** [comment]
> Please provide more information about your setup. Package version, device model, flutter version, etc.


Same error here. 

Package version : 0.7.0
Device model : Pixel 5 emulator 
Flutter version: 3.24.0 (stable)

Error happens when opening a file

`final pdf = PdfImageRendererPdf(path: path);`
`await pdf.open();`
